# -*- coding: utf-8 -*-
"""pyscf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eNmhaW9bhkGiWSUBq0DtZ98Ozh98rvak
"""

!pip install pyscf

from pyscf import gto, scf

# 分子の定義
mol = gto.M(atom='H 0 0 0; F 0 0 1.1', basis='ccpvdz')

# Hartree-Fock計算の実行
mf = scf.RHF(mol)
energy = mf.kernel()
print('Energy:', energy)

!wget https://ma.issp.u-tokyo.ac.jp/wp-content/uploads/sites/3/2019/04/h2mol.py

!python h2mol.py > log

!head -2 results.dat

!plot results.dat
